# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [148]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [149]:
a1 = pd.Series([100,200,300,400])

Print a, and data type

In [150]:

a1

0    100
1    200
2    300
3    400
dtype: int64

In [151]:
type(a1)

pandas.core.series.Series

Using indexing access the element 300 from the series a.

In [152]:
print(a1[2])

300

What are the values of index for series a?

In [153]:
a1.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [154]:
a1 = pd.Series([100, 200, 300, 400], index=["a", "b", "c", "d"])

# Rearrange to the new index order
a1 = a1.reindex(["c", "a", "b", "d"])
a1

c    300
a    100
b    200
d    400
dtype: int64

Access the value in the series with index 'd'

In [155]:
a1.loc["d"]

np.int64(400)

Sort the values wrt to the index and print it

In [156]:
a1.sort_index()

a    100
b    200
c    300
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [157]:
b = pd.Series([800,450,100], index=['e','f','g'])
b

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [158]:
a1 = pd.concat([a1,b])

In [159]:
#print a again after appending b into it

a1

c    300
a    100
b    200
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [160]:
a1 = a1.sort_index()
a1

a    100
b    200
c    300
d    400
e    800
f    450
g    100
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [161]:
df = pd.DataFrame(a1)

In [162]:
df

     0
a  100
b  200
c  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [163]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [164]:
# yep its same as the series.

a1.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [165]:
df.head()  # top 5

     0
a  100
b  200
c  300
d  400
e  800

In [166]:
df.tail()    #bottom 5

     0
c  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [167]:
df.columns= ["Numbers"]
df

   Numbers
a      100
b      200
c      300
d      400
e      800
f      450
g      100

In [168]:
df.rename(columns={'Numbers': 'points'}, inplace=True)
df

   points
a     100
b     200
c     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [169]:
#Create fruits array
import numpy as np
fruits = ['orange','mango','apple']

In [170]:
#Create series fruits out of fruits array
fruits = pd.Series(np.random.choice(fruits, size=7))
fruits

0     mango
1     apple
2     mango
3    orange
4     apple
5     mango
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [171]:
fruits.index = df.index

fruits

a     mango
b     apple
c     mango
d    orange
e     apple
f     mango
g     apple
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [172]:
fruits = pd.DataFrame(fruits, columns = ["fruits"])

In [173]:
fruits

   fruits
a   mango
b   apple
c   mango
d  orange
e   apple
f   mango
g   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [174]:
d1 = {
    "city" : ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
"Temperature" : [15, 22, 20, 26,-2]}

d1 = pd.DataFrame(d1)

Print(d1)

In [175]:
d1

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [176]:
d1.shape

(5, 2)

Set city = d1['city']

In [177]:
city = d1['city']

print city <br>
What is the type of city.

In [178]:

print(city)
city.dtype

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

dtype('O')

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [179]:
d2 = { "city" : ['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    "Temperature" : [24,35,36,39]}

d2 = pd.DataFrame(d2)

print the shape of this dataframe

In [180]:
d2
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [181]:
d3 = pd.merge(d1, d2, on=['city','Temperature'], how='outer')
d3

          city  Temperature
0    Bengalaru           24
1   Chandigarh           15
2      Chennai           26
3   Coimbatore           35
4        Delhi           22
5       Kanpur           20
6       Manali           -2
7  Pondicherry           39
8    Srirangam           36

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [182]:
d3[d3['Temperature'] <=20]

         city  Temperature
1  Chandigarh           15
5      Kanpur           20
6      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [183]:
d3[d3['Temperature'] >= 35]

          city  Temperature
3   Coimbatore           35
7  Pondicherry           39
8    Srirangam           36

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [184]:
# write function here

def is_ut(x):
    if x in ['Chandigarh', 'Pondicherry', 'Delhi']:
        return True
    else:
        return False

d3['Union Territory'] = d3['city'].apply(is_ut)

In [147]:
d3

          city  Temperature  Union Territory  temp_farenhit
0    Bengalaru           24            False           75.2
1   Chandigarh           15             True           59.0
2      Chennai           26            False           78.8
3   Coimbatore           35            False           95.0
4        Delhi           22             True           71.6
5       Kanpur           20            False           68.0
6       Manali           -2            False           28.4
7  Pondicherry           39             True          102.2
8    Srirangam           36            False           96.8

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [185]:
# write function here

def c_to_f(temp):
    temp = (temp*(9/5)) +32
    return temp

In [186]:
# check function c_to_f(10)
temperature = int(input("Temperature"))
print(c_to_f(temperature))

Temperature10
50.0

In [187]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhit'] = d3['Temperature'].apply(c_to_f)
d3

          city  Temperature  Union Territory  temp_farenhit
0    Bengalaru           24            False           75.2
1   Chandigarh           15             True           59.0
2      Chennai           26            False           78.8
3   Coimbatore           35            False           95.0
4        Delhi           22             True           71.6
5       Kanpur           20            False           68.0
6       Manali           -2            False           28.4
7  Pondicherry           39             True          102.2
8    Srirangam           36            False           96.8

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [188]:
d3[d3['Union Territory'] == True],['city'],['Union Territory']

(          city  Temperature  Union Territory  temp_farenhit
 1   Chandigarh           15             True           59.0
 4        Delhi           22             True           71.6
 7  Pondicherry           39             True          102.2,
 ['city'],
 ['Union Territory'])

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [189]:
d3[d3['temp_farenhit'] > 90],['city']

(          city  Temperature  Union Territory  temp_farenhit
 3   Coimbatore           35            False           95.0
 7  Pondicherry           39             True          102.2
 8    Srirangam           36            False           96.8,
 ['city'])

Select only the first three rows of the dataframe d1.

In [190]:
d3.head(3)

         city  Temperature  Union Territory  temp_farenhit
0   Bengalaru           24            False           75.2
1  Chandigarh           15             True           59.0
2     Chennai           26            False           78.8

Select all the rows and last two columns in the dataframe.

In [191]:
d3[['Union Territory','temp_farenhit']]

   Union Territory  temp_farenhit
0            False           75.2
1             True           59.0
2            False           78.8
3            False           95.0
4             True           71.6
5            False           68.0
6            False           28.4
7             True          102.2
8            False           96.8

## Groupby

In [192]:
# Create a dataframe using dictionary of your choice
data = { 'Name': ['Prerna','Shiv','John','ALice','John'],
         'age' : [23,54,46,43,32],
         'score':[80,65,90,78,96],
        'dept' : ['IT','Law','HR','Marketing','IT']}

data = pd.DataFrame(data)
data

     Name  age  score       dept
0  Prerna   23     80         IT
1    Shiv   54     65        Law
2    John   46     90         HR
3   ALice   43     78  Marketing
4    John   32     96         IT

In [193]:
# Use Groupby of single column with aggregate sum()
data.groupby('dept')['score'].sum()

dept
HR            90
IT           176
Law           65
Marketing     78
Name: score, dtype: int64

In [194]:
# Use Groupby of single column with aggregate count()

data.groupby('dept')['score'].count().loc[lambda x:x > 1]

dept
IT    2
Name: score, dtype: int64

In [195]:
# Use Groupby of single column with aggregate min() and max()

data.groupby('score').min()

         Name  age       dept
score
65       Shiv   54        Law
78      ALice   43  Marketing
80     Prerna   23         IT
90       John   46         HR
96       John   32         IT

In [196]:
data.groupby('dept')['age'].max()

dept
HR           46
IT           32
Law          54
Marketing    43
Name: age, dtype: int64

In [197]:
# Use Groupby of any 2 columns with aggregate mean()

data.groupby(['dept','Name'])['score'].mean()

dept       Name
HR         John      90.0
IT         John      96.0
           Prerna    80.0
Law        Shiv      65.0
Marketing  ALice     78.0
Name: score, dtype: float64

In [198]:
# Use Groupby of any 2 columns with aggregate min() and max()

data.groupby(['dept','Name'])['score'].agg(['min','max'])

                  min  max
dept      Name
HR        John     90   90
IT        John     96   96
          Prerna   80   80
Law       Shiv     65   65
Marketing ALice    78   78